CookieTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('test-cookie/', views.test_cookie),
    path('test-session/', views.test_session),
    path('random-string/', views.random_string),
]

products/urls.py
from django.urls import path
from .import views
app_name = 'products'

urlpatterns = [
	path('', views.product, name = 'product'),
	path('addtocart/<int:pk>', views.addtocart, name = 'addtocart'),
	path('viewCart/', views.viewCart, name = 'viewCart'),
	path('deleteCart/<int:id>', views.deleteCart, name = 'deleteCart'),
	path('updateCart/', views.updateCart, name = 'updateCart'),
]

blog/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

# Create your models here.
STATUS = (
	('active', 'active'),
	('inactive', 'inactive')
	)
class Products(models.Model):
	title = models.CharField(max_length = 25)
	image = models.FileField()
	description = models.TextField()
	price = models.FloatField()
	created_at = models.DateTimeField(auto_now_add = True)
	status = models.CharField(max_length = 25, choices = STATUS)

	def __str__(self):
		return f"{self.title} -- {self.status}"

class Order(models.Model):
	customer = models.CharField(max_length = 25)
	product = models.ForeignKey(Products, on_delete = models.CASCADE)
	quantity = models.IntegerField()
	price = models.FloatField()
	created_at = models.DateTimeField(auto_now_add = True)

	def __str__(self):
			return f"{self.customer} -- {self.product} --- {self.quantity}"

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.crypto import get_random_string

def test_cookie(request):
	if not request.COOKIES.get('random'):
		response = HttpResponse('first visiting')
		lstring = get_random_string(length = 20)
		response.set_cookie('random', lstring, 60*60*24*30)
		return response
	else:
		return HttpResponse('your random cookie is ' + str(request.COOKIES['random']))

def random_string(request):
	s = get_random_string(length = 20)
	return HttpResponse(s)

def test_session(request):
	if not request.session.get('fruit'):
		request.session['fruit'] = 'banana'
		return HttpResponse('create session success')
	else:
		return HttpResponse('your session is ' + request.session['fruit'])

products/views.py
from django.shortcuts import render, redirect
from .models import Products, Order
from django.utils.crypto import get_random_string
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate

# Create your views here.
def product(request):
	listproduct = Products.objects.filter(status = 'active')
	return render(request, 'products/listproduct.html', {'product': listproduct})

def addtocart(request, pk):
	# nếu user login, ta add vào bảng order bình thường
	# nếu chưa login ta sẽ tạo cookie (nếu chưa có cookie) và add vô bảng như user login
	# quan trong là khi bảng order sẽ có quá nhiều dữ liệu dạng guest giỏ hàng thì phải xóa đi sau 1 thời gian nhất định với ebay =90 days => tạo 1 code chạy để xác định xem cái nào = 90 thông qua created_at trong bảng Order
	product = Products.objects.get(pk = pk)
	
	if request.user.is_authenticated:
		customer = Order.objects.filter(customer = request.user)

		if customer.exists():
			if Order.objects.filter(customer = request.user, product = product).exists():
				customerExit = Order.objects.get(customer = request.user, product = product)
				customerExit.quantity += 1
				customerExit.save()
				messages.success(request, 'your add more than 1 item in your cart')

			else:
				Order.objects.create(
					customer = request.user,
					product = product,
					quantity = 1,
					price = product.price
				)
				messages.info(request, 'your add 1 item in your cart')

		else:
			Order.objects.create(
				customer = request.user,
				product = product,
				quantity = 1,
				price = product.price
			)
			messages.info(request, 'your add 1 item in your cart')

	else:
		if not request.COOKIES.get('customer'):
			customer = get_random_string(length = 25)
			response.set_cookie('customer', customer, 60*60*24*30)

			Order.objects.create(
				customer = customer,
				product = product,
				quantity = 1,
				price = product.price
			)	
			messages.info(request, 'your add 1 item in your cart')
		else:
			customerExit = Order.objects.filter(customer = str(request.COOKIES['customer']), product = product)
			if customerExit.exists():
				customerExit = Order.objects.get(customer = str(request.COOKIES['customer']), product = product)
				customerExit.quantity += 1
				customerExit.save()
				messages.warning(request, 'your add more than 1 item in your cart')

			else:
				Order.objects.create(
					customer = str(request.COOKIES['customer']),
					product = product,
					quantity = 1,
					price = product.price
				)
				messages.info(request, 'your add 1 item in your cart')

	return redirect('products:product')

def viewCart(request):
	total = 0
	if request.user.is_authenticated:
		yourCart = Order.objects.filter(customer = request.user)
		if yourCart.exists():
			for item in yourCart:
				total += item.price * item.quantity
			return render(request, 'products/viewCart.html', {'yourCart': yourCart, 'total': total})
		else:
			messages.info(request, 'your cart do not have any product')
			return render(request, 'products/viewCart.html', {'total': total})
	else:
		yourCart = Order.objects.filter(customer = str(request.COOKIES['customer']))
		if yourCart.exists():
			for item in yourCart:
				total += item.price * item.quantity
			return render(request, 'products/viewCart.html', {'yourCart': yourCart, 'total': total})
		else:
			messages.info(request, 'your cart do not have any product')
			return render(request, 'products/viewCart.html', {'total': total})

def deleteCart(request, id):
	product = Products.objects.get(id=id)
	Order.objects.filter(product = product).delete()
	return redirect('products:viewCart')

def updateCart(request):
	id = request.POST.get('id')
	number = request.POST.get('number')

	product = Products.objects.get(id = id)
	Order.objects.filter(product=product).update(quantity = number)
	return redirect('products:viewCart')

products/templates/products/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
	  <!-- Brand -->
	  <a class="navbar-brand" href="#">ConanKun</a>

	  <!-- Links -->
	  <ul class="navbar-nav">
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'products:product' %}">Products</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'products:viewCart' %}">Cart</a>
	    </li>
	  </ul>
	</nav>
	
	{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{message.tags}} alert-dismissible">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <strong>{{message}}</strong>
	</div>
	{% endfor %}
	{% endif %}

	<div class="container">
	{% block content %}
	
	{% endblock %}
	</div>
	<script>
	  	function updateCart(id){
	  		var number = $("#quantity_"+id).val();

	  		$.post("{% url 'products:updateCart' %}", 
	  			{'id': id, 'number': number, 'csrfmiddlewaretoken': '{{csrf_token}}' }, 
	  			function(data){
	  				window.location.href = "{% url 'products:viewCart' %}";
	  		});
	  	}
	  </script>
</body>
</html>

products/templates/products/listproduct.html
{% extends 'products/base.html' %}
{% block content %}
	<div class="row">
		{% for item in product %}
		<div class="card col-md-4" style="width:400px">
		  <img class="card-img-top" src="/media/{{item.image}}" alt="Card image">
		  <div class="card-body">
		    <h4 class="card-title">Title: {{item.title}}</h4>
		    <p class="card-text">Description: {{item.description}}</p>
		    <p class="card-text font-weight-bold">Price: ${{item.price}}</p>
		    <p><a href="{% url 'products:addtocart' item.pk %}" class="btn btn-info">AddtoCart</a><a href="#" class="mx-3 btn btn-danger">Buy It Now</a></p>
		  </div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

products/templates/products/viewCart.html
{% extends 'products/base.html' %}
{% block content %}
	 <table class="table table-striped">
	    <thead>
	      <tr>
	        <th>Product</th>
	        <th>Price</th>
	        <th>Quantity</th>
	        <th>Delete</th>
	      </tr>
	    </thead>
	    <tbody>
    	{% for cart in yourCart %}
	      <tr>
	        <td>{{cart.product}}</td>
	        <td>${{cart.price}}</td>
	        <td>x <input type="number" min="1" value="{{cart.quantity}}" id="quantity_{{cart.product.id}}" onclick="updateCart({{cart.product.id}})"></td>
	        <td><a href="{% url 'products:deleteCart' cart.product.id %}" title="">Delete</a></td>
	      </tr>
      	{% endfor %}
      	<tr>
      		<td class="font-weight-bold">TOTAL: ${{total |floatformat:2}}</td>
      	</tr>
	    </tbody>
	  </table>
	  
{% endblock %}